RTSP_URL =  "rtsp://username:password@camera_ip"

CONFIDENCE = 0.4

SAM_UPDATE_INTERVAL = 15
POSE_UPDATE_INTERVAL = 10

FRAME_WIDTH = 1280
FRAME_HEIGHT = 720

GROUP_DISTANCE = 100

INTERACTION_TIME = 5

MOVEMENT_THRESHOLD = 0.5

MOVEMENT_WEIGHT = 0.7
ORIENTATION_WEIGHT = 0.3